### PR TITLE
v0.9 of Classical Extras

### PR DESCRIPTION
**Pull request by MetaTunes**
Major additions to functionality - see full version history in readme for details

### CODE REVIEW

**Comment by MetaTunes** [comment]
Changes that were made by @Sophist-UK to v0.7 (creating v0.8) have been included in this version 0.9

**Comment by MetaTunes** [comment]
Only remaining Codacy issue is re use of eval. Recommended approach of using ast.literal_eval does not seem to work with Picard.
Conflicts need to be resolved by @Sophist-UK as they are caused by a minor amendment being made to version 0.7 which occurred after changes I made to the original version. These amendments have been incorporated in version 0.9 so the conflict should be resolved by simply replacing the existing version with this new one.

**Comment by Sophist-UK** [comment]
1. These merge conflicts arise because you haven't based the branch of your own repo on the current version in this repo. You need to rebase your own branch in order to address the merge conflicts or resolve them here.

2. It is not my responsibility to resolve the conflicts. My responsibility finished when my PR was accepted and merged. But even if I was inclined to resolve the conflicts, I do not have the rights needed to do so.

**Comment by MetaTunes** [comment]
OK I will rebase them. In future I would appreciate it if I was contacted before people decide to make changes.

**Comment by MetaTunes** [comment]
I could use a bit of help as to resolve this. It seems that I do not have the necessary permissions to resolve the (very minor) conflicts here, but if I attempt to rebase by re-forking the branch, it seems to assume that my commit is OK and won't pick up the previous version. Do I need to reverse the commit first, or could someone with the necessary permissions resolve the conflicts? I only use Git for this, so it's not easy for me to see how to fix it.

**Comment by Sophist-UK** [comment]
Well, the normal way to do a PR is to keep your 1.0 branch in line with the picard-plugins 1.0 branch, and to create a new branch for your PR (say classical_extras_0.9).

Then if you based your new branch on an old version of 1.0, after you brought 1.0 up to date you would do a `git rebase 1.0` from your branch to set the base correctly.

But you have made the changes in your own 1.0, I have no idea how to fix it in your own repo.

Do you have options on this page to fix the merge issues?

**Comment by Sophist-UK** [comment]
> OK I will rebase them. In future I would appreciate it if I was contacted before people decide to make changes.

That is not how Open Source works. Please don;t blame me because you are having difficulties with Git.

**Comment by MetaTunes** [comment]
>Do you have options on this page to fix the merge issues?

I do, but when I tried that (see the last merge 1.0 into 1.0) - it showed the conflicts as resolved when I edited them and the merge as being clean, but still shows them as unresolved here after the merge.

**Comment by MetaTunes** [comment]
>But you have made the changes in your own 1.0, I have no idea how to fix it in your own repo.

If I fork the existing 1.0 it just merges it with my commits in my repo and says that the branches can be automatically merged - i.e. no conflicts - whereas when I did the original PR it did say that there were conflicts. So I am very confused as to whether any conflicts remain.

**Comment by Sophist-UK** [comment]
Well - I am not a Git expert, but I am not sure you are using the terminology correctly as "fork ... merges with my commits in my repo" doesn't seem to make any sense to me. I think you can try two things:

1. Rebase 1.0 against upstream/1.0. Then do a force push to Github.

2. Close this PR. Save your code. Delete your fork i.e. your repo on Github. Refork, Create a new branch for the PR. Save your new code to that branch. Resubmit the PR.

**Comment by MetaTunes** [comment]
Given the above, should I just do a new PR (and if so, what do I do about this one). I don't want to really foul things up!
- crossed in the ether - I was referring to the prev post

**Pull request closed without merging**
