### PR TITLE
Add my keep and padded plugins

### PR DESCRIPTION
**Pull request by mineo**

### CODE REVIEW

**Comment by mineo** [comment]
Ping?

**Comment by Sophist-UK** [comment]
Look like useful plugins - but I am surprised that you don't have merge capabilities yourself.

**Comment by Sophist-UK** [comment]
@dufferzafar - I don't suppose you want to add @Mineo as an admin of this repo?

**Comment by dufferzafar** [comment]
I just have merge rights, not the admin privileges. I guess they lie with @mwiencek

**Pull request merged**
