### PR TITLE
Add GPL license details to standardise_performers.py

### PR DESCRIPTION
**Pull request by Sophist-UK**

### CODE REVIEW

**Comment by phw** [comment]
I would suggest using short license strings like GPL2 or GPL3 for `PLUGIN_LICENSE`. This makes the licenses better machine readable and allows for a more flexible display e.g. on the Picard website.

**Comment by phw** [comment]
Or see my comment on http://tickets.musicbrainz.org/browse/PICARD-703

**Comment by Sophist-UK** [comment]
I will change all my PRs once the license list is agreed.

**Comment by phw** [comment]
Yeah, I suggest we even merge all the PRs and later change them all in one go. Once we have a license for the plugins that's easy to do :)

**Comment by Sophist-UK** [comment]
I standardised them to be the same as @phw's Video tools plugin.

**Pull request merged**
