### PR TITLE
Metabrainz/2.0

### PR DESCRIPTION
**Pull request by MetaTunes**
Update Classical Extras plugin to v2.0.7

### CODE REVIEW

**Review by phw — APPROVED** [review]
Looking good to me.

I tested the new column feature a bit with the current development version. I found it rather confusing to setup and I probably did not fully understand the functionality, but as far as I can tell it is compatible with the new configurable columns in the upcoming 2.3 release :)

**Comment by MetaTunes** [comment]
The configurable columns functionality was something I originally wrote to help me quickly review test results, but then I decided to leave it in as others might find it useful. I’ll do a forum post on it and am open to suggestions for improvements. :)

**Comment by MetaTunes** [comment]
I’ll do the forum post as soon as the new version is merged and published to the plugins site ;)

**Comment by MetaTunes** [comment]
There is a v small bug - PR for fix shortly
Done

**Comment by phw** [comment]
> There is a v small bug - PR for fix shortly

Allright, I'll merge this one for now and await the bugfix PR. We would like to do a beta release of the upcoming 2.3 release before end of January, likely this will also be the time when we update the website.

**Comment by MetaTunes** [comment]
The bug was fixed in this PR

**Comment by phw** [comment]
All good then, thanks

**Pull request merged**
