### PR TITLE
theaudiodb: Add option to use high resolution images

### PR DESCRIPTION
**Pull request by phw**
Ads an option to use high resolution images for cover art from TheAudioDB.

One example with such cover art available is:

https://www.theaudiodb.com/album/2349438
https://musicbrainz.org/release-group/2587b239-ca88-47ec-907c-33d0b22ff915

### CODE REVIEW

**Comment by zag2me** [comment]
Cool thanks, I was thinking about making this some kind of premium feature in the future but for now its all good :) Hopefully it will encourage more to upload 4K covers.
Bandwidth is quite expensive...

**Comment by phw** [comment]
@zag2me I also couldn't find much about it, after long digging I found one example (but I already lost the URL again). But let me know if I should restrict this in the plugin or nag people more. It has not yet been released to the official plugin downloads :D

**Comment by Sophist-UK** [comment]
In my experience a significant proportion of people who want 4k covers will generally upload if they find one isn't there - so IMO making it possible / easy to tag your music with 4K covers is likely to encourage uploads as you suggest. That said, I think that TheAudioDB charging for access to 4K pictures will negate much of this, and I would prefer to see MB offering / encouraging 4K album art via e.g. Cover Art Archive.

So if it were me, I would:

a. Put something on the Album Art tab for Releases on MB to either show the 4K art if MB already has it or to encourage people to upload it if they have it themselves.

b. If a Picard user has enabled 4K cover art, then put something in Picard to encourage / help people to find and upload the 4K cover art to MB.

Bandwidth for 4K covers might be significant when you are bulk-downloading the covers whilst tagging, but still relatively small by comparison with e.g. video streaming (even at 720p).

I would be more concerned about having this enabled by default when (I am guessing that) the majority of people won't want 4K pictures (at least not for a few years anyway).

**Comment by zag2me** [comment]
No need to restrict for now, I'm happy to provide this feature and let it grow. 

As @Sophist-UK  says maybe it should be "opt in" check box to control the growth.

I only mentioned it as I need to keep an eye on the bandwidth as it may not be sustainable in the long term 👍  We already serve terabytes a day.

**Pull request merged**
