### PR TITLE
Classical Extras v 0.7

### PR DESCRIPTION
**Pull request by MetaTunes**
This plugin replaces the the previous (withdrawn) Classical Work Parts. It has been extensively reworked and enhanced.
It populates hidden variables in Picard with information from the MusicBrainz database about the recording, artists and work(s), and of any containing works, passing up through mutiple work-part levels until the top is reached.
The "Options" page (Options->Options->Plugins->Classical Extras) allows the user to determine how these hidden variables are written to file tags, as well as a variety of other options.
This plugin is particularly designed to assist with tagging of classical music so that player or library manager software which can display multiple work levels and different artist types can have access to them.

### CODE REVIEW

**Comment by sambhav** [comment]
Wow, this is a BIG PR. Can I ask you to first of all remove all the binary files that aren't needed? I can see zips, jpgs. Please remove the clutter and keep only the py files.

**Review by sambhav — CHANGES_REQUESTED** [review]
Next I think you should take a look at the codacy review and try to fix them https://www.codacy.com/app/MetaBrainz/picard-plugins/pullRequest?prid=816806

**Comment by MetaTunes** [comment]
Codacy issues are fixed. I'll remove the zip file. The jpgs are used by the readme. Where should they go?

**Comment by sambhav** [comment]
You can upload the jpegs on imgur.

**Comment by MetaTunes** [comment]
All binary files now removed. Remaining files are the two pys, the ui from Qt and the Readme.md.
I recommend reading the readme first to gain an overview of the intended functionality.

**Comment by MetaTunes** [comment]
Is there anything further for me to do, or is this OK for review now?

**Comment by zas** [comment]
> Is there anything further for me to do, or is this OK for review now?

You could run [autopep8](https://pypi.python.org/pypi/autopep8) on your files to make them [PEP8](https://www.python.org/dev/peps/pep-0008/)-friendly, before we merge.

**Review by zas — APPROVED** [review]

**Review by sambhav — APPROVED** [review]

**Review by zas — CHANGES_REQUESTED** [review]
This PR contains changes from master that should be removed, sorry for the inconvenience.
We clarified branches: 1.0 for Picard < 2.0 and 2.0 for Picard 2, but your PR was based on master.

If you need help to clean the mess, ask @samj1912 or me

**Comment by MetaTunes** [comment]
Ah, I started this before it was split into 1.0 and 2.0. What is the best way to resolve it? Should I close this PR, do a new fork and a new PR, or is there a simpler approach?

**Comment by sambhav** [comment]
@MetaTunes  you may simply rebase your commits to 1.0

**Comment by MetaTunes** [comment]
Sorry, I'm still learning GitHub. I've been using GitHub desktop for Windows, but that doesn't seem to give an option to rebase and I can no longer load the master branch into it. So not sure where to go from here.

**Comment by MetaTunes** [comment]
GitHub on Windows working again (suspect W10 prob as usual). I have attempted to rebase, but not sure if I've done it right. Please advise.

**Comment by zas** [comment]
> Sorry, I'm still learning GitHub. I've been using GitHub desktop for Windows, but that doesn't seem to give an option to rebase and I can no longer load the master branch into it. So not sure where to go from here.

If you don't want to bother with `git rebase`, and don't mind to lose the history, you may just start over:
- clone latest picard-plugins, branch 1.0 (which is the default)
- copy `classical_extras` directory and its contents from the messy clone
- make a new clean PR including ONLY the new files

BTW, the situation is even worser after your last pushes, it now contains twice the number of commits ;)

**Comment by MetaTunes** [comment]
Looks like I rebased vs the wrong branch. Maybe re-clone etc would be best!

**Comment by MetaTunes** [comment]
Looks like I rebased vs the wrong branch. Have issued new PR #110 to replace this one.

**Comment by MetaTunes** [comment]
Closed this PR - replaced by #110

**Pull request closed without merging**
