### PR TITLE
New simpler version of Abbreviate Artist Sort

### PR DESCRIPTION
**Pull request by Sophist-UK**
Different output so different version rather than an upgrade.

Muh simpler algorithm based on regex.

### CODE REVIEW

**Comment by samj1912** [comment]
@Sophist-UK please rebase this against the correct branch of PP that you want to merge this into.

**Comment by mineo** [comment]
What's the difference to the existing abbreviate artist sort plugin? The pull request mentions different output, the plugins description just mentions that the output is written to different variables. If it's only the latter, I would prefer not having a completely separate plugin whose only difference can be achieved by a few `set` calls in the tagger script.

**Comment by Sophist-UK** [comment]
@mineo Instead of `Bach, J.S.` it outputs `Bach JS` because:

a. Removing commas seems important when artists are generally separated by commas.
b. Removing periods seems important when classical artist strings are generally very long.

And instead of putting the output in new variables, it replaces existing variables so that it can coexist with e.g. Title Case, Standardise feat. etc.

I didn't want to replace the existing plugin because that would impact users tagging.

(Incidentally, the code utilises regex replacements rather than a convoluted string processing loop.)

**Comment by Sophist-UK** [comment]
@samj1912 Rebase done.

**Comment by sambhav** [comment]
LGTM :+1:

**Review by zas — APPROVED** [review]

**Comment by sambhav** [comment]
You might want to consider renaming the plugin? or release it as a newer versio of the abbriviate plugin?

**Comment by Sophist-UK** [comment]
I did both. But:

1. The way it needs to be used has changed - so it is not compatible with the existing version and can't be a version upgrade.
2. Yet it still does essentially the same thing just with better functionality and better performance. So it shouldn't be called something different.

**Comment by Sophist-UK** [comment]
This is ready to merge - the codacy issues are for the in-built unit testing using assert statements that are not a genuine issue.

**Pull request merged**
