### PR TITLE
Add multi-value variables for artist types and join phrases

### PR DESCRIPTION
**Pull request by rdswift**
Note:  This PR replaces #320 

As discussed in the [Community Forum](https://community.metabrainz.org/t/artist-variables-plugin/409544/13) this update provides the following new multi-value variables:

* **_artists_album_all_types** - All album artist types, as a multi-value
* **_artists_album_all_join_phrases** - All album artist join phrases, as a multi-value
* **_artists_track_all_types** - All track artist types, as a multi-value
* **_artists_track_all_join_phrases** - All track artist join phrases, as a multi-value

I had to add a default value of **'[blank]'** for join phrases consisting of an empty string because Picard removes empty strings from a multi-value in [line 436 of picard.metadata.py](https://github.com/metabrainz/picard/blob/6ac0501f55f2df6dd5e5f032dbedfb226467665f/picard/metadata.py#L432-L441)::

    def set(self, name, values):
        name = self.normalize_tag(name)
        if isinstance(values, str) or not isinstance(values, Iterable):
            values = [values]
        values = [str(value) for value in values if value or value == 0]     # This is the line #
        if values:
            self._store[name] = values
            self.deleted_tags.discard(name)
        elif name in self._store:
            del self[name]

This seems like a bit of a hack, but can work in scripts if the user does an appropriate `$replace()` for the default value.

@zas / @phw do you know off hand if changing this to:

    def set(self, name, values):
        name = self.normalize_tag(name)
        if isinstance(values, str) or not isinstance(values, Iterable):
            values = [values]
        values = [str(value) for value in values if value or value == 0 or value == '']
        if values and (len(values) > 1 or values[0]):
            self._store[name] = values
            self.deleted_tags.discard(name)
        elif name in self._store:
            del self[name]

would break things, other than the two tests that I know fail (`test_cmd_setmulti_custom_splitter_string` and `test_cmd_setmulti_will_remove_empty_items`)?  Is there another (better) way to preserve empty string elements in a multi-value variable, or is that something that we just do **not** want to do?

### CODE REVIEW

**Comment by phw** [comment]
> would break things, other than the two tests that I know fail

Not sure, maybe people have some scripts where empty values can happen in multi value context. Like `$set(foo,)`  results in foo not being written to files I'd also expect that empty values do not get written to files.

So this probably means empty values in variables sometimes make sense (like here), but more often I'd not expect them to be part. What about maybe using a zero width space (`\u200B`) in this case?

**Comment by rdswift** [comment]
> So this probably means empty values in variables sometimes make sense (like here), but more often I'd not expect them to be part. What about maybe using a zero width space (`\u200B`) in this case?

That probably works okay for display of the tags, but causes a problem if the tag is used in the file naming script, because Picard does not strip `\u200B` out of the path when saving (at least on my Windows 7 system).  Is this something that we might want to do by default (stripping `\u200B` from written paths)?

**Comment by phw** [comment]
> Is this something that we might want to do by default (stripping `\u200B` from written paths)?

This might be actually useful. Not sure if someone has a use case of having a path with this character?

**Comment by rdswift** [comment]
> Not sure if someone has a use case of having a path with this character?

The only thing that comes to mind is some rudimentary attempt to lock a directory or file so it is unavailable to those that don't know about it, which doesn't seem to make a lot of sense to me.

My suggestion is to go ahead with it and see if anyone complains.  In the worst case, we could always add yet another option setting in the File Naming section to keep it.  I'll have a look at it and see if I can come up with a PR.

**Review by phw — APPROVED** [review]

**Pull request merged**
