### PR TITLE
PICARD-2153: Classical Extras context sensitive help

### PR DESCRIPTION
**Pull request by Sophist-UK**
Support standard Options help button link to Classical Extras help pages

### CODE REVIEW

**Review by phw — CHANGES_REQUESTED** [review]
Makes sense, but version number should be bumped to trigger updates.

Just a question on the URL: Is this kind of "official" for the plugin, or who is maintaining it? The site is pretty cool and comprehensive, didn't know about it. But wonder if this will stay available and up to date.

**Comment by rdswift** [comment]
I'm guessing it's somewhat official because it is the same as the README in @MetaTunes repository (fork) for [Classical Extras](https://github.com/MetaTunes/picard-plugins/tree/metabrainz/2.0/plugins/classical_extras), and the link on the first line refers to "my github site".

I wonder if it might be more appropriate to request to apply this change to the original @MetaTunes repository / fork?

**Comment by Sophist-UK** [comment]
> Makes sense, but version number should be bumped to trigger updates.

Ooops.
 
> Just a question on the URL: Is this kind of "official" for the plugin, or who is maintaining it? The site is pretty cool and comprehensive, didn't know about it. But wonder if this will stay available and up to date.

This is the same URL that is linked to on the Help tab of the plugins Options page. The plugin owner maintains it, But we could consider asking him to migrate it to the Picard documentation page so it is all in one place.

**Comment by Sophist-UK** [comment]
> I wonder if it might be more appropriate to request to apply this change to the original @MetaTunes repository / fork?

I could do that but Mark would have to then submit a PR here anyway.

**Comment by Sophist-UK** [comment]
@MetaTunes Ping.

**Comment by MetaTunes** [comment]
Thanks for the heads-up. I will be turning to this shortly. I do try and maintain everything. I've been a bit busy with PHP stuff lately which messes my head for Python etc. I would prefer it if any changes can be passed through me and I will update my repository and submit PR. Hopefully will get to this in a week or so.

**Comment by Sophist-UK** [comment]
Apologies Mark for doing this direct.

**Review by phw — APPROVED** [review]

**Comment by phw** [comment]
@MetaTunes I'm going ahead and merge this for now here directly. Would be great to incorporate this then in your upstream branch of course.

**Pull request merged**
