### PR TITLE
replaygain: Added license details

### PR DESCRIPTION
**Pull request by phw**
Contributors to this plugin are @phw (myself), @garyvdm, @lalinsky, @mineo, @zas and @DanMan

See https://github.com/musicbrainz/picard/commits/master/contrib/plugins/replaygain

Would be great if you could leave a short comment if you are fine with this licensing.

### CODE REVIEW

**Comment by zas** [comment]
Fine for me.

**Comment by phw** [comment]
I would also ask everybody involved to also comment if this decision can be applied to other plugins as well. I assume it will be ok for the core team members, but having this done properly is still the best :)

**Comment by lalinsky** [comment]
Fine with me of course :)

**Comment by mineo** [comment]
Fine by me (both this plugin and my contributions to other plugins in picard contrib folder).

**Comment by DanMan** [comment]
I added 3 characters. Sure. :)

**Comment by zas** [comment]
Only @garyvdm approval is lacking.

**Comment by zas** [comment]
> Only @garyvdm approval is lacking.

That's a long time now, and still no approval from @garyvdm (which isn't on github anymore).
What should we do ?

**Comment by garyvdm** [comment]
Sorry. Somehow I missed this before.

I approve of the change.

**Pull request merged**
